name: Sync README to Notion

on:
  push:
    branches:
      - 'main'
    paths:
      - 'README.md'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync_readme_to_notion:
    runs-on: ubuntu-latest
    name: Checkout and upload Readme to Notion
    steps:
      - name: checkout
        uses: "actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b"
      - name: Upload to Notion
        uses: agonzalezl/readme-to-notion-action@88b6cb8eea354ac61c589f540e40cacadf0c8ecb
        with:
          file-path: 'README.md'
          notion-token: ${{ secrets.NOTION_TOKEN }}
          notion-page-id: ${{ secrets.NOTION_PAGE_ID }}
